/**
 * Complaint formatting and generation utilities
 * Helps structure complaint data for government portal submission
 */

/**
 * Format complaint details into structured text for portal
 */
export const formatComplaintForPortal = (result, details, evidenceList) => {
  const timestamp = new Date().toLocaleString('en-IN', { 
    dateStyle: 'medium', 
    timeStyle: 'short', 
    timeZone: 'Asia/Kolkata' 
  });

  const scamType = result?.scamTypes?.[0]?.type || 'Unknown Scam';
  const riskLevel = result?.scamTypes?.[0]?.riskLevel?.toUpperCase() || 'UNKNOWN';
  const messagePreview = result?.text?.slice(0, 500) || 'N/A';

  return {
    incidentSummary: `INCIDENT REPORT
Report Generated: ${timestamp}
Scam Type: ${scamType}
Risk Assessment: ${riskLevel}
Severity Score: ${result?.score || 0}/100`,

    incidentDetails: `INCIDENT DETAILS
Date of Incident: ${details.dateOfIncident || 'N/A'}
Time of Incident: ${details.timeOfIncident || 'Not specified'}
Platform/Channel: ${details.platformUsed || 'N/A'}
Description: ${details.incidentDescription || 'No description provided'}`,

    transactionDetails: details.transactionAmount || details.transactionMethod ? `TRANSACTION DETAILS
Amount: ${details.transactionAmount ? '₹' + details.transactionAmount : 'Not specified'}
Method: ${details.transactionMethod || 'Not specified'}` : null,

    suspectDetails: details.suspectName || details.suspectPhone || details.suspectEmail || details.suspectAccount ? `SUSPECT INFORMATION
Name/Username: ${details.suspectName || 'Not available'}
Phone Number: ${details.suspectPhone || 'Not available'}
Email: ${details.suspectEmail || 'Not available'}
Account/ID: ${details.suspectAccount || 'Not available'}` : null,

    messageAnalyzed: `SUSPICIOUS MESSAGE ANALYZED
"${messagePreview}${messagePreview.length >= 500 ? '...' : ''}"

Key Indicators Detected:
${result?.highlightedKeywords?.slice(0, 5).map((k, i) => `${i + 1}. ${k}`).join('\n') || '• Suspicious patterns identified'}`,

    recommendedActions: `RECOMMENDED IMMEDIATE ACTIONS
1. Do NOT respond to the message or sender
2. Do NOT click any links or download attachments
3. Do NOT share personal details, passwords, or OTPs
4. Block the sender immediately on the platform
5. Report to your bank if financial fraud is suspected
6. Change passwords for compromised accounts
7. Monitor your accounts for unauthorized transactions
8. File this complaint with cybercrime authorities immediately`,

    evidenceSummary: evidenceList && evidenceList.length > 0 ? `EVIDENCE & ATTACHMENTS
${evidenceList.length} file(s) attached:
${evidenceList.map((e, i) => `${i + 1}. ${e.originalName}`).join('\n')}` : null,

    additionalNotes: details.additionalNotes ? `ADDITIONAL INFORMATION
${details.additionalNotes}` : null
  };
};

/**
 * Generate formatted complaint text combining all sections
 */
export const generateFormattedComplaint = (result, details, evidenceList) => {
  const sections = formatComplaintForPortal(result, details, evidenceList);
  
  const complaintText = [
    sections.incidentSummary,
    '',
    '─────────────────────────────────────────────────────────',
    '',
    sections.incidentDetails,
    '',
    sections.messageAnalyzed,
    '',
    sections.transactionDetails || '',
    sections.transactionDetails ? '' : null,
    sections.suspectDetails || '',
    sections.suspectDetails ? '' : null,
    '',
    '─────────────────────────────────────────────────────────',
    '',
    sections.recommendedActions,
    '',
    sections.evidenceSummary || '',
    sections.evidenceSummary ? '' : null,
    sections.additionalNotes || '',
    sections.additionalNotes ? '' : null,
    '',
    '─────────────────────────────────────────────────────────',
    'Generated by CyberSaathi - Cybercrime Response Platform',
    'File this complaint on cybercrime.gov.in within 2 hours for best recovery chances',
    '─────────────────────────────────────────────────────────'
  ]
  .filter(line => line !== null && line !== '')
  .join('\n');

  return complaintText;
};

/**
 * Generate copy-friendly structured sections for guided filling
 */
export const generatePortalSections = (result, details, evidenceList) => {
  const sections = formatComplaintForPortal(result, details, evidenceList);
  
  return [
    {
      title: 'Incident Summary',
      value: sections.incidentSummary,
      icon: 'document',
      helpText: 'Copy this to the "Incident Description" field'
    },
    {
      title: 'Date & Time',
      value: `Date: ${details.dateOfIncident || 'N/A'}\nTime: ${details.timeOfIncident || 'Not specified'}`,
      icon: 'calendar',
      helpText: 'Fill date and time fields separately on the portal'
    },
    {
      title: 'Platform Information',
      value: `Platform/Channel: ${details.platformUsed || 'N/A'}`,
      icon: 'device',
      helpText: 'Select the appropriate platform on the portal'
    },
    {
      title: 'Detailed Description',
      value: details.incidentDescription || 'No description provided',
      icon: 'text',
      helpText: 'Copy to the full description field'
    },
    ...(details.transactionAmount || details.transactionMethod ? [{
      title: 'Financial Details',
      value: `Amount: ${details.transactionAmount ? '₹' + details.transactionAmount : 'None'}\nMethod: ${details.transactionMethod || 'Not specified'}`,
      icon: 'money',
      helpText: 'Fill financial details section if applicable'
    }] : []),
    ...(details.suspectName || details.suspectPhone || details.suspectEmail || details.suspectAccount ? [{
      title: 'Suspect Information',
      value: `Name: ${details.suspectName || 'Unknown'}\nPhone: ${details.suspectPhone || 'Unknown'}\nEmail: ${details.suspectEmail || 'Unknown'}\nAccount: ${details.suspectAccount || 'Unknown'}`,
      icon: 'user',
      helpText: 'Fill suspect details if available'
    }] : []),
    {
      title: 'Message Content',
      value: result?.text || 'No message provided',
      icon: 'message',
      helpText: 'Include the suspicious message in your complaint'
    },
    {
      title: 'Recommended Actions',
      value: sections.recommendedActions,
      icon: 'checkmark',
      helpText: 'List of immediate actions to be taken'
    }
  ];
};

/**
 * Validation function to check if complaint details are sufficient
 */
export const validateComplaintDetails = (details) => {
  const errors = [];
  
  if (!details.incidentDescription?.trim()) {
    errors.push('Incident description is required');
  }
  
  if (!details.dateOfIncident?.trim()) {
    errors.push('Date of incident is required');
  }
  
  if (!details.platformUsed?.trim()) {
    errors.push('Platform/channel is required');
  }

  return {
    isValid: errors.length === 0,
    errors
  };
};

/**
 * Generate portal link with pre-filled parameters if available
 */
export const getPortalLink = () => {
  return 'https://cybercrime.gov.in/webform/complaint/';
};

/**
 * Prepare data for government portal submission
 */
export const prepareForPortalSubmission = (result, details, evidenceList) => {
  const validation = validateComplaintDetails(details);
  
  if (!validation.isValid) {
    return {
      success: false,
      errors: validation.errors,
      message: 'Please fill required fields before proceeding'
    };
  }

  return {
    success: true,
    complaintText: generateFormattedComplaint(result, details, evidenceList),
    sections: generatePortalSections(result, details, evidenceList),
    portalUrl: getPortalLink(),
    timestamp: new Date().toISOString()
  };
};
